Optimize URL rewriting by compiling regex once during BackendService initialization
Frontman-Labs/frontman pull request #105
Opened 2023-04-08 13:29 UTC by hyperioxx

## Description

This pull request improves the performance of the URL rewriting feature by compiling the regex only once during the BackendService initialization and storing it as a field in the BackendService struct. This eliminates the need to compile the regex on every request.

## Added Features

- Added a compiledRegex field to the BackendService struct to store the compiled regex.
- Modified the Init() method in BackendService to compile the regex during initialization.

## Bug Fixes

Optimized URL rewriting by avoiding regex compilation on every request.

## Breaking Changes

None

## Checklist:
- [ ] I have added tests to my code
- [ ] I have commented my code, particularly in complex areas
- [ ] I have made the necessary changes to README.md

2023-04-08 16:32 UTC, CCOLLOT approved these changes

2023-04-08 16:48 UTC, amityahav commented
@hyperioxx ive commented , don't merge just yet

2023-04-08 19:44 UTC, hyperioxx commented
@amityahav i can't see your comments, they might be in the "review" stage

2023-04-08 20:21 UTC, amityahav commented
@hyperioxx tagged you , but if you can't see in brief I think:
1. The compiledRegex car should be remanded to be more informative
2. Also the GetMatch function
3. The whole compile Regex logic should be in the validateService function instead and then we can remove it's call from the init func

2023-04-08 23:02 UTC, hyperioxx commented
@amityahav I've made the changes, can you look again please :)

2023-04-09 07:07 UTC, amityahav commented
@hyperioxx can u see my new comment?

2023-04-09 08:47 UTC, hyperioxx commented
No dude @amityahav

2023-04-09 09:02 UTC, amityahav commented
@hyperioxx its ugly but the compilePath function should be called as well in the init function because this function will load the services upon crash for example. So here this function would be called twice because the first call is for validation. Do you have any idea how to make it less uglier?

2023-04-09 09:40 UTC, hyperioxx commented
@amityahav try now

2023-04-09 09:48 UTC, amityahav requested changes

2023-04-09 10:02 UTC, hyperioxx commented on api/api.go
>  	service.Init()
Could just have a validate function ?

```golang
func (bs *BackendService) ValidatePath() error {
	if bs.RewriteMatch == "" || bs.RewriteReplace == "" {
		return nil
	}

	_, err := regexp.Compile(bs.RewriteMatch)
	if err != nil {
		return err
	}

	return nil
}
```

2023-04-09 10:19 UTC, amityahav approved these changes

2023-04-09 10:19 UTC, merged